Add Judger implementation
beepboop271/duber-judge pull request #4
Opened 2021-01-18 17:15 UTC by candicezzzzz

Adds the judge package for submission testing and grading.

To judge a submission, create an instance of `Judger` and call `.judge(Submission)`. The `Judger` then proceeds to:
1. Get a source checker to check if the source code contains predefined illegal segments, depending on the language of the submission. If the source code does contain any of the segments, or the language is not supported, the Judger updates the status of the submission accordingly and judging ends.
2. Get a `SourceLauncher` by calling `SourceLauncherService.getSourceLauncher(...)` and try to setup the program. The `SourceLauncher` is responsible for creating a temporary file for the program and setting up the program (e.g. compilation). If the language is not supported, or some internal exceptions occur, the Judger updates the status of the submission accordingly and judging ends.
3. Repeatedly call `Tester.test(...)` for each of the testcase in the problem, which returns the result of the testcase run. Inside each batch of problem, if one of the testcase run fails, the rest are skipped. Otherwise, if all testcases pass, the submission gets the points of the batch. To track the memory usage of the child processes, all programs are launched via `GlobalChildProcessService.launchChildProcess(..)`. If time or memory limit exceeds, the program is forcibly terminated. 
4. Update the submission's stats (score, run duration, memory usage, status), and write it back to the database. Currently, the entities in `src/entities/` are a simplified version, thus no actual db writing is implemented yet.

See `judge.class.violet.html` for further details.

2021-01-21 08:05 UTC, beepboop271 requested changes
- I am assuming that the entities are fine.
- Many times the launched process throws an exception because its PID cannot be determined due to:
  - Various other random subprocesses being spawned (can be fixed by checking process name before considering it).
  - The program completes too quickly and exits before being able to poll its PID (ie your "a = 1" python test).
- You put public on pretty much every class for some reason
- Your subpackages make no sense and it looks like you arbitrarily put classes in them (why are source checkers and source launchers "entities" when they do things like a "service"?). You can have one judge package or you can split it up sanely, perhaps one package for *Checker, one for *Launcher...
- Might want to consider renaming some classes
- Your versions conflict with Joseph's versions
- Random blank lines near the end of files, missing `this.` and missing `Class.staticThing` in places
- Some sketchy exception handling with some copy paste there too
- You need to split up some big methods
(see comments for examples of some entries)

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/test/Main.java
> +    }
Don't run your test submissions sequentially. It's slow and does not represent a more realistic load where the web server threads can call into judge concurrently. Adding this many submissions at the same time would be more like a worst-case load for our program though.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/test/Main.java
> +    File directory = new File("cache/judge/");
`cache` is a bad folder name for this purpose. A cache is for something you quickly read from often. You are reading from the files once and deleting them right after.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/test/Main.java
> +      Runtime.getRuntime().availableProcessors(),
Might not be the best choice of thread pool size, but that doesn't matter too much for now.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/UserException.java
> +@SuppressWarnings("serial")
Add a serial version ID (you can just start with 0) instead of suppressing the warning.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/Judger.java
> +  }
Your code is not supposed to know about the database at all.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/Judger.java
> +  public Submission judge(Submission submission) {
This method is way too long.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/Judger.java
> +    }
3 things:
- There really isn't much point to using a name other than `e` for caught exceptions in my opinion.
- You can simplify this weird structure into the following using `|`.
- You should probably move the copy pasted failure lines into another method.
```java
} catch (CompileErrorException e) {
  return fail(ExecutionStatus.COMPILE_ERROR, e, launcher, submission);
} catch (UserException | InternalErrorException e) {
  return fail(ExecutionStatus.INTERNAL_ERROR, e, launcher, submission);
}

// the copy pasted params that are the same each time go to the
// end of the param list for fail(interesting_stuff, boring_stuff)
// instead of fail(boring_stuff, interesting_stuff)
private Submission fail(status, exception, launcher, submission) {
  submission.setStatus(status);
  e.printStackTrace();
  launcher.close();
  return submission;
}
```
Note that if you follow the other advice in `SourceLauncherService`, the `launcher.close()` line would be removed from this particular catch block.

This comment applies to all the other `catch` blocks too, it's just that this one in particular made my want to comment.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/Judger.java
> +      for (int j = 0; j < testcases.length; j++) {
The contents of this loop just scream "make a new method". An indent size of 2 spaces doesn't mean you can have 7 indents.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/Judger.java
> +            run = caseRunFuture.get();
What happened to running batches concurrently?

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/SourceLauncher.java
> +  public void setup() throws InternalErrorException, UserException {
`throws InternalErrorException, CompileErrorException`

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/SourceLauncherService.java
> +  }
The whole point of making all the parts future based was so that the file writing and compiling can happen asynchronously if needed (though we need it to be synchronous because the program needs to be setup before running it). However, you haven't included any blocking tasks (except for the optional temp directory creation) in this part at all, and in `Judger` you call `launcher.setup()` which is the method that synchronously creates all the necessary files (on the thread created by the web server).

So just move setup into this runnable so that the actual blocking part is run in the thread pool. I guess keeping the file stuff in the thread pool should also ensure that there's no way you'd ever get hit with 100 requests on the web server at the same time causing 100 files to be written at the same time and it would be done slowly.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/PythonLauncher.java
> +    ProcessBuilder builder = new ProcessBuilder("python", this.getSource().getAbsolutePath());
Reminder that the exact commands need to be customizable (e.g, the command might to be `python3` or perhaps an absolute executable path).

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/JavaLauncher.java
> +  }
You forgot to put files into their own folder like I said to. The class files will overwrite each other. In addition, this is an example of one of the ways your PID checker could fail unless you check for the name of the process, since `javac` would appear as a new child process.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/entities/JavaLauncher.java
> +    ProcessBuilder builder = new ProcessBuilder("java", this.getSource().getAbsolutePath());
`java RandomJavaFile.java` does not work. You'll need to do `java -cp path Main` where `path` is the directory to the folder containing `Main.class`. Alternatively, you can have the command `java Main` and then change the working directory of the `ProcessBuilder` to be the directory containing the class file.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/SourceLauncherService.java
> +public class SourceLauncherService {
Perhaps rename to `ProgramLauncher` to be more consistent with `ProgramChecker` -> `SourceChecker` -> `Java`/`PythonChecker`. You're also missing a private constructor here.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/Tester.java
> +      }
What is this exception handling...

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/Tester.java
> +}
Blank lines? Note that this happens many times, I'm just leaving a comment on one example to point it out.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/Tester.java
> +    public void run() {
This method is also pretty long.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/Tester.java
> +        }
Why are you copying bytes one at a time when StringBuilder can use `System.arraycopy` when you append char arrays. Note that you will need to change your `new BufferedInputStream(program.getInputStream())` to use `new InputStreamReader(program.getInputStream())` (to read characters instead of bytes, and don't use a `BufferedReader` because you're doing buffering). This is fine because all program input/output should be done with ascii characters. You can just read in 1 or several kilobytes at a time (8k if you want to be the same as `BufferedReader`), not like the output limit will be very small. I believe you do this elsewhere too.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/Tester.java
> +          if (sb.toString().trim().equals(expectedOutput.trim())) { // trim whitespace
Don't forget to document somewhere that leading and trailing whitespaces are not significant, but whitespace between is.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +public class GlobalChildProcessService {
I think the name `ChildProcesses` is adequate (e.g. Collections has static methods for Collection, Files has static methods for File, Arrays has static methods for...).

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +  private static final int UPDATE_INTERVAL_MILLIS = 1000*1;
Does this have to be fixed? Perhaps maybe wait 1 second (or just suspend the thread entirely) when you're not running something and then a shorter time/wake up the thread when you are.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +    LinkedHashSet<Integer> updatedProcessPids = new LinkedHashSet<Integer>();
Why is this a LinkedHashSet?

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +        }
As mentioned above, you could try replacing this with something more intelligent, such as using `Object.wait()` and `Object.notify()`.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +          Math.max(memoryUsedKb, childProcess.getMemoryUsedKb())
Maybe change ChildProcess.setMemoryUsedKb to have some other name (updateMemoryUsageKb?) and always take max into account in that method so that an external class can't just set whatever it wants.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +    OsProcess parentProcessTree = SYSTEM_MONITOR.processTree();
You should `.find` the current pid here so that you dont need to always walk from root later in the method.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +        double memoryUsedKb = childInfo.getTotalBytes()/1024.0;
`childInfo.getResidentBytes()`
No need to penalize them for memory they aren't even really using.

2021-01-21 08:05 UTC, beepboop271 commented on src/judge/services/GlobalChildProcessService.java
> +    int childProcessPid = GlobalChildProcessService.getNewPid(updatedProcessPids);
It might be nice to make it easier to swap between Java >= 9 and Java < 9 methods of getting PID.

2021-01-23 23:18 UTC, candicezzzzz commented
Fixed most issues addressed:
- Improved packaging and class naming
- Batch testing is now concurrent
- Fixed pid tracking issues, and used `Object.wait()` and `Object.notify()` to monitor child processes
- Program files are now separated into their own folders, and java submissions are able to compile and run
    - The class has to be named `Main`
Pending fixes:
- Make illegal strings customizable (by external classes, via a Settings object or a static method)
- Make launcher commands customizable

2021-08-22 21:39 UTC, merged